export const CLEAR_USERDATA = 'CLEAR_USERDATA';
export const LOG_USER_FAILURE = 'LOG_USER_FAILURE';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_PENDING = 'LOG_USER_PENDING';
export const LOG_OUT = 'LOG_OUT';